name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "server/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "server/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run tests
        working-directory: ./server
        run: npm test

      - name: ESLint
        working-directory: ./server
        run: npx eslint .
